- name: Apache Server
  hosts: newcoreoshosts
  sudo: false
  become_method: su
  tasks:
    - name: Start etcd
      service: name=etcd.service state=started

    - name: Install docker-py
      pip: 
        name=docker-py
        version=1.3.1

    - name: Prepare fsdeployer env
      file: path=~/fsdeployer state=directory mode=0755

    - name: Turn off StrictHostKeyChecking
      shell: ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa && \ 
             ssh-keyscan github.com >> /home/ansible/.ssh/known_hosts && \
             eval $(ssh-agent) && \
             ssh-add /home/ansible/.ssh/id_rsa && \
             echo -e "Host *\n\tStrictHostKeyChecking=no\nForwardAgent yes" >> /home/ansible/.ssh/ssh_config

    - git: repo=https://github.com/jpazdyga/fsdeployer.git
       dest=/tmp/fsdeployer
       version=master
       accept_hostkey=True

    - name: Deploy the app
      shell: cd /tmp/fsdeployer; ./deploy.sh '{{ giturl }}' '{{ domain }}'
      sudo: true
